-- ═══════════════════════════════════════════════════════════════════════
-- Project Manager — CATCH-UP MIGRATION
--
-- Generated by concatenating schema-v3.sql through schema-v7.sql, which as of
-- this writing had not been applied to the live database. Every one of them is
-- idempotent, so running this whole file is safe even if some parts were
-- already applied.
--
-- Run in Supabase: Dashboard → SQL Editor → New query → paste → Run.
--
-- schema.sql and schema-v2.sql are assumed to already be applied (they are —
-- profiles/projects/tasks/categories/statuses all exist). If you are setting
-- up a brand-new project, run those two first.
-- ═══════════════════════════════════════════════════════════════════════



-- ─────────────────────────────────────────────────────────────────────
-- schema-v3.sql
-- ─────────────────────────────────────────────────────────────────────

-- Project Manager — schema addition for delete requests. Members can't
-- delete tasks directly; instead they submit a request that an Admin
-- reviews and approves/rejects from Settings → Delete Requests.
-- Idempotent — safe to re-run.
-- Run in Supabase: Dashboard → SQL Editor → New query → paste → Run.

create table if not exists public.delete_requests (
  id           uuid primary key default gen_random_uuid(),
  task_id      uuid references public.tasks(id) on delete set null,
  project_id   uuid not null references public.projects(id) on delete cascade,
  requested_by uuid references public.profiles(id) on delete set null,
  task_name    text not null,
  status       text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at   timestamptz not null default now(),
  resolved_at  timestamptz
);

alter table public.delete_requests enable row level security;

drop policy if exists "delete_requests_select" on public.delete_requests;
create policy "delete_requests_select" on public.delete_requests
  for select using (public.is_admin() or requested_by = auth.uid());

drop policy if exists "delete_requests_insert" on public.delete_requests;
create policy "delete_requests_insert" on public.delete_requests
  for insert with check (public.can_access_project(project_id));

drop policy if exists "delete_requests_update" on public.delete_requests;
create policy "delete_requests_update" on public.delete_requests
  for update using (public.is_admin());

do $$ begin
  alter publication supabase_realtime add table public.delete_requests;
exception when duplicate_object then null; end $$;


-- ─────────────────────────────────────────────────────────────────────
-- schema-v4.sql
-- ─────────────────────────────────────────────────────────────────────

-- Project Manager — schema additions for cross-manager read-only visibility and
-- an impersonation audit trail. Idempotent — safe to re-run.
-- Run in Supabase: Dashboard → SQL Editor → New query → paste → Run.

-- ── Managers can view (read-only) other managers' projects/tasks/comments ──
-- The Admin's own personally-managed projects stay invisible to managers —
-- this is keyed off the *project's assigned manager's role*, not a separate
-- "private" flag, so nothing needs backfilling on existing rows.
create or replace function public.can_view_project(pid uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select public.can_access_project(pid)
    or (
      public.is_manager()
      and exists (
        select 1 from public.projects p
        join public.profiles mgr on mgr.id = p.manager_id
        where p.id = pid and mgr.role = 'manager'
      )
    );
$$;

drop policy if exists "projects_select" on public.projects;
create policy "projects_select" on public.projects
  for select using (public.can_view_project(id));

drop policy if exists "project_members_select" on public.project_members;
create policy "project_members_select" on public.project_members
  for select using (public.can_view_project(project_id));

drop policy if exists "categories_select" on public.categories;
create policy "categories_select" on public.categories
  for select using (public.can_view_project(project_id));

drop policy if exists "tasks_select" on public.tasks;
create policy "tasks_select" on public.tasks
  for select using (public.can_view_project(project_id));

drop policy if exists "comments_select" on public.comments;
create policy "comments_select" on public.comments
  for select using (
    exists (select 1 from public.tasks t where t.id = task_id and public.can_view_project(t.project_id))
  );

-- The one write action a cross-viewing manager gets: feedback comments.
drop policy if exists "comments_insert" on public.comments;
create policy "comments_insert" on public.comments
  for insert with check (
    exists (select 1 from public.tasks t where t.id = task_id and public.can_view_project(t.project_id))
  );

-- Every other write policy (projects/tasks/categories/project_members
-- insert/update/delete) is intentionally left on can_access_project /
-- can_manage_project — unchanged — so this really is read-only.

-- ── Impersonation audit trail ───────────────────────────────────────────
-- "Switch to" (src/app/(app)/impersonate-actions.ts) logs into here so
-- there's a record of who acted as whom and when, given how much trust
-- full act-as impersonation carries. Admin-only visibility; no UI reads
-- this yet, it's just captured in case it's ever needed.
create table if not exists public.impersonation_log (
  id          uuid primary key default gen_random_uuid(),
  actor_id    uuid references public.profiles(id) on delete set null,
  target_id   uuid references public.profiles(id) on delete set null,
  started_at  timestamptz not null default now(),
  ended_at    timestamptz
);

alter table public.impersonation_log enable row level security;

drop policy if exists "impersonation_log_select_admin" on public.impersonation_log;
create policy "impersonation_log_select_admin" on public.impersonation_log
  for select using (public.is_admin());

-- Written exclusively via the service-role client from impersonate-actions.ts
-- (which bypasses RLS after verifying the caller's role itself, same pattern
-- as every other service-role write in this codebase) — no insert/update
-- policy needed for anon/authenticated roles.


-- ─────────────────────────────────────────────────────────────────────
-- schema-v5.sql
-- ─────────────────────────────────────────────────────────────────────

-- Project Manager — two additions:
--   1. any user (including members) can create their own projects, and
--      whoever created a project owns it for permission purposes;
--   2. self-service password changes become requests an Admin approves.
-- Idempotent — safe to re-run.
-- Run in Supabase: Dashboard → SQL Editor → New query → paste → Run.

-- ── Who "owns" a project ────────────────────────────────────────────────
-- The assigned manager if there is one, otherwise whoever created it. This
-- is what decides how much of a project other managers may see.
create or replace function public.project_owner_role(pid uuid)
returns public.app_role language sql stable security definer set search_path = public as $$
  select coalesce(
    (select pr.role from public.projects p
       join public.profiles pr on pr.id = p.manager_id
      where p.id = pid),
    (select pr.role from public.projects p
       join public.profiles pr on pr.id = p.created_by
      where p.id = pid)
  );
$$;

-- ── Any signed-in user may create a project ─────────────────────────────
drop policy if exists "projects_insert" on public.projects;
create policy "projects_insert" on public.projects
  for insert with check (auth.uid() is not null);

-- ── Ownership grants access, regardless of role ─────────────────────────
-- Adds two things to the previous definition:
--   1. the creator can work in their own project even if they're a member;
--   2. managers get full access to member-owned projects, matching the
--      "managers oversee users" rule (admin-owned projects stay private,
--      and other managers' projects stay read-only via can_view_project).
create or replace function public.can_access_project(pid uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select public.is_admin()
    or exists (select 1 from public.projects p where p.id = pid and p.manager_id = auth.uid())
    or exists (select 1 from public.projects p where p.id = pid and p.created_by = auth.uid())
    or exists (select 1 from public.project_members pm where pm.project_id = pid and pm.user_id = auth.uid())
    or (public.is_manager() and public.project_owner_role(pid) = 'member');
$$;

create or replace function public.can_manage_project(pid uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select public.is_admin()
    or exists (select 1 from public.projects p where p.id = pid and p.created_by = auth.uid())
    or (public.is_manager() and (
      exists (select 1 from public.projects p where p.id = pid and p.manager_id = auth.uid())
      or public.project_owner_role(pid) = 'member'
    ));
$$;

-- can_view_project (schema-v4.sql) is unchanged — it still layers read-only
-- cross-manager visibility on top of can_access_project. Every policy calls
-- these functions rather than inlining the logic, so redefining them here is
-- enough; no policies need rewriting.

-- ── Password change requests ────────────────────────────────────────────
-- A user setting their own password no longer applies it directly; it files
-- a request the Admin approves from Settings → Password Requests. The
-- proposed password is stored with the same AES-256-GCM encryption used by
-- public.credentials (src/lib/crypto.ts) so the Admin can review it before
-- approving and the approval can actually apply it.
create table if not exists public.password_change_requests (
  id                 uuid primary key default gen_random_uuid(),
  user_id            uuid not null references public.profiles(id) on delete cascade,
  encrypted_password text not null,
  status             text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at         timestamptz not null default now(),
  resolved_at        timestamptz
);

alter table public.password_change_requests enable row level security;

-- Rows are written and resolved exclusively by server actions using the
-- service-role client (which encrypts/decrypts with the server-only key),
-- so only a read policy is needed here.
drop policy if exists "password_change_requests_select" on public.password_change_requests;
create policy "password_change_requests_select" on public.password_change_requests
  for select using (public.is_admin() or user_id = auth.uid());

do $$ begin
  alter publication supabase_realtime add table public.password_change_requests;
exception when duplicate_object then null; end $$;


-- ─────────────────────────────────────────────────────────────────────
-- schema-v6.sql
-- ─────────────────────────────────────────────────────────────────────

-- Project Manager — members add and edit freely; only Admins and Managers
-- delete. Idempotent — safe to re-run.
-- Run in Supabase: Dashboard → SQL Editor → New query → paste → Run.

-- schema-v5.sql let whoever created a project manage it, which also handed
-- members the ability to delete. Split those apart:
--   can_manage_project  → "may DELETE things here"  (Admins + Managers only)
--   can_edit_project    → "may CHANGE things here"  (+ the project's creator)
-- Members still route task deletions through delete_requests (schema-v3.sql).

create or replace function public.can_manage_project(pid uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select public.is_admin()
    or (public.is_manager() and (
      exists (
        select 1 from public.projects p
        where p.id = pid and (p.manager_id = auth.uid() or p.created_by = auth.uid())
      )
      or public.project_owner_role(pid) = 'member'
    ));
$$;

create or replace function public.can_edit_project(pid uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select public.can_manage_project(pid)
    or exists (select 1 from public.projects p where p.id = pid and p.created_by = auth.uid());
$$;

-- Categories: anyone who can work in the project may add and rename them.
-- (categories_insert already allows this; categories_delete stays
-- Admin/Manager-only via can_manage_project.)
drop policy if exists "categories_update" on public.categories;
create policy "categories_update" on public.categories
  for update using (public.can_access_project(project_id));

-- The project itself: its creator can rename/reschedule it, but projects_delete
-- stays on can_manage_project so they can't delete it.
drop policy if exists "projects_update" on public.projects;
create policy "projects_update" on public.projects
  for update using (public.can_edit_project(id));

-- Unchanged on purpose, so members can add and edit but never delete:
--   tasks_insert / tasks_update      → can_access_project  (add + edit)
--   tasks_delete                     → can_manage_project  (delete requests instead)
--   categories_delete                → can_manage_project
--   projects_delete                  → can_manage_project
--   project_members_insert/delete    → can_manage_project  (staffing is a
--                                      manager job; the UI never offers it
--                                      to members)


-- ─────────────────────────────────────────────────────────────────────
-- schema-v7.sql
-- ─────────────────────────────────────────────────────────────────────

-- Project Manager — delete requests can now cover whole projects, not just
-- tasks. Idempotent — safe to re-run.
-- Run in Supabase: Dashboard → SQL Editor → New query → paste → Run.

-- delete_requests (schema-v3.sql) was task-only. `kind` tells the two apart:
--   'task'    → task_id points at the task to delete
--   'project' → task_id is null; project_id IS the target
-- Existing rows are all task requests, hence the default.
alter table public.delete_requests
  add column if not exists kind text not null default 'task';

do $$ begin
  alter table public.delete_requests
    add constraint delete_requests_kind_check check (kind in ('task', 'project'));
exception when duplicate_object then null; end $$;

-- task_name doubles as the display label for both kinds — it holds the
-- project's name on a 'project' request. It's captured at request time on
-- purpose, so Settings can still say what was deleted after the row it
-- pointed at is gone.
comment on column public.delete_requests.task_name is
  'Display name of whatever is being deleted: the task name, or the project name when kind = ''project''.';

-- Members can't delete a project directly (projects_delete stays on
-- can_manage_project, per schema-v6.sql) but they can ask. The existing
-- delete_requests_insert policy already allows anyone with project access to
-- file a request, so nothing further is needed here.
